config/routes.rb
Rails.application.routes.draw do

  namespace :api, :defaults => {:format => :json} do
    resources :recipes
  end

  devise_for :users, :controllers => { 
    :registrations => "users/registrations",
    :sessions => "sessions"
  }

  as :user do
    post 'sign_in' => 'sessions#create'
    delete 'sign_out' => 'sessions#destroy'
    delete 'logout' => 'sessions#logout'
  end
  
#  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  #root to: "welcome#index"
  resources :recipes do
  	resources :reviews, except: [:show, :index]
  end
#  root "recipes#index"
  root "categories#index"
  get 'search_recipes', to: "recipes#search"
  resources :categories
  resources :ingredients
end

app/models/recipe.rb
class Recipe < ApplicationRecord
	belongs_to :user

	has_many :ingredients
	has_many :instructions

	has_many :recipe_categories
  has_many :categories, through: :recipe_categories

  has_many :recipe_ingredients
  has_many :ingredients, through: :recipe_ingredients

  has_many :reviews

	accepts_nested_attributes_for :ingredients,
  								reject_if: proc { |attributes| attributes['name'].blank? },
  								allow_destroy: true
 	accepts_nested_attributes_for :instructions,
  								reject_if: proc { |attributes| attributes['step'].blank? },
  								allow_destroy: true

  validates :name, :description, :image, presence: true

	has_attached_file :image, styles: { :medium => "400x400#" }
	validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/

  def self.search(search)
    where("name LIKE ?", "%#{search}%") 
  end
end

app/controllers/api/recipes_controller.rb
class Api::RecipesController < ApplicationController

	before_action :require_user, only: [:create]

  def index
    @recipes = Recipe.all
    @ingredients = Ingredient.all

    # @recipes=Recipe.find(params[:id])
    # @find_recipes.ingredients.each do |i|
    # 	i.name
    # end

    respond_to do |format|
      format.json { render :json => {:recipes => @recipes, :ingredients => @ingredients} }
    end
  end

  def create
    ingredient_names = params[:ingredients]
    new_ingredients = ingredient_names.map { |name| Ingredient.create(name: name) }

    recipe =  Recipe.create(
                user: current_user,
                ingredients: new_ingredients,
                name: params[:name],
                description: params[:description]
              )

    if recipe.valid?
      render json: recipe
    else
      render json: { errors: recipe.errors.full_messages}, status: :unprocessable_entity
    end
  end

end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
	before_action :find_recipe, only: [:show, :edit, :update, :destroy]
	before_action :authenticate_user!, except: [:index, :show]

	require 'openfoodfacts'
	require 'json'

	def index
		@recipes=Recipe.all
		if params[:search]
			@recipes = Recipe.search(params[:search]).order("created_at DESC")
		else 
			 @recipes = Recipe.all.order('created_at DESC')
		end
	end

	def show
		 @reviews = Review.where(recipe_id: @recipe.id).order("created_at DESC")
		  if @reviews.blank?
      	@avg_review = 0
    	else
      	@avg_review = @reviews.average(:rating).round(2)
    	end
	end

	def new
		@recipe = current_user.recipes.new
		@ingredients = Ingredient.where(hb: true)
	end

	def create
		@recipe = current_user.recipes.new(recipe_params)
		if @recipe.save
			flash[:notice] = "Successfully created a new recipe"
			redirect_to @recipe
		else
			render :action => :new
		end
	end

	def edit
		@ingredients = Ingredient.where(hb: true)
	end

	def update
		if @recipe.update(recipe_params)
			redirect_to @recipe
		else
			render :action => :edit
		end
	end

	def destroy
		@recipe.destroy
		flash[:notice] = "Successfully deleted the recipe"
		redirect_to :action => :index
	end

	private

	def recipe_params
#		params.require(:recipe).permit(:name, :description, :image, :rating, ingredients_attributes: [:id, :name, :_destroy], instructions_attributes: [:id, :step, :_destroy], :ingredient_ids => [], category_ids: [])
		params.require(:recipe).permit(:name, :description, :image, :rating, ingredients_attributes: [:name, :_destroy], instructions_attributes: [:id, :step, :_destroy], :ingredient_ids => [], category_ids: [])
	end

	def find_recipe
		@recipe = Recipe.find(params[:id])
	end
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/recipes/_form.html.erb
<div class="container"> 
  <%= simple_form_for @recipe, html: { multipart: true } do |f| %>
    <% if @recipe.errors.any? %>
      <div>
        <p>
          <%= @recipe.errors.count %>
          Prevented this recipe from saving
        </p>
        <ul>
          <% @recipe.errors.full_messages.each do |msg| %>
            <li>
              <%= msg %>
            </li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <div class="panel-body"> 
      <%= f.input :name, input_html: { class: 'form-control' }%>
      <%= f.input :description, as: :text, input_html: { class: 'form-control', :cols => 5, :rows => 10 } %>
      <%= f.input :image %>
      <div><%= f.label "Categories" %></div>
      <div class="form-group">
        <div class="row">
          <div class="checkbox checkbox-primary">
        <%= f.collection_check_boxes(:category_ids, Category.all, :id, :name) do |cb| %>
        <% cb.label {cb.check_box + cb.text} %>
        <% end %>
          </div>
       </div>
      </div>
      <div><%= f.label "Select Honestbee Ingredients" %></div>
      <div class="form-group">
        <div class="row">
        </div>
      </div>
      <!--<div>
          <%#= f.select :ingredient_ids, Ingredient.all.map{ |c|
            [c.name, c.id] } %>
      </div>-->
      <div class="row">
        <div class="col-md-6">
          <h3>Ingredients</h3>
          <div>
            <%= f.simple_fields_for :ingredients do |ingredient| %>
              <%= render 'ingredient_fields', f: ingredient %>
            <% end %>
            <div>
              <%= link_to_add_association 'Add Ingredient', f, :ingredients, class: "btn btn-default add-button" %>
            </div>
          </div>
        </div>
        <div class="col-md-6">
          <h3>Instructions</h3>
          <div>
            <%= f.simple_fields_for :instructions do |instruction| %>
              <%= render 'instruction_fields', f: instruction %>
            <% end %>
            <div>
              <%= link_to_add_association 'Add Step', f, :instructions, class: "btn btn-default add-button" %>
            </div>
          </div>
        </div>
      </div>
    </div>
    <%= f.button :submit, class: "btn btn-primary" %>
  <% end %>
</div>

app/views/recipes/_ingredient_fields.html.erb
<div class='nested-fields'>
    <%= f.input :name %>
    <%= link_to_remove_association "remove step", f %>
</div>

app/views/recipes/_instruction_fields.html.erb
<div class='nested-fields'>
    <%= f.input :step, as: :text, input_html: { class: 'form-control', :cols => 5, :rows => 10 } %>
    <%= link_to_remove_association "remove step", f %>
</div>

app/views/recipes/_post.html.erb
<div class="row">
  <% object.each do |recipe| %>
   <div class="col-md-4">
      <%= link_to recipe do %>
          <div class="thumbnail">
            <%= image_tag recipe.image.url(:medium), class: "recipe_image"  %>
            <div class="caption">
            <h3><%= link_to recipe.name, recipe %></h3>
           <!-- <p>  <%#= recipe.description %> </p>-->
            </div>
          </div>
          <!--  <%# if recipe.categories.any? %>
            <p>Categories: <%#= render recipe.categories %></p>
             <%# end %> -->
            <% end %>
    </div>
  <% end %>
</div>

      

app/views/recipes/_posting.html.erb
<% object.each do |recipe| %>
              <%= link_to recipe do %>
                <div class="thumbnail">
                <%= image_tag recipe.image.url(:medium), class: "recipe_image"  %>
                <div class="caption">
                  <h3><%= link_to recipe.name, recipe %></h3>
                  <p>  <%= recipe.description %> </p>
          <% end %>
 <% end %>

app/views/recipes/edit.html.erb
<div class="container"> 
	<h1> Edit Recipe</h1>
		<%= render 'form' %>
	<br>
	<div>
		<%= link_to "Back", root_path, class: "btn btn-default" %>
	</div>
</div>

app/views/recipes/index.html.erb
<div class="container">
  <%#= link_to "New Recipe", new_recipe_path, class: "btn btn-lg btn-default" %>
  <%#= link_to "List all Categories", categories_path ,class: "btn btn-lg btn-default" %>
  <%#= link_to "List all Ingredients", ingredients_path ,class: "btn btn-lg btn-default" %>
 <!-- <div>
    <h3>Search for Recipes</h3>
    <%= form_tag recipes_path, :method => 'get' do %>
    <div class="form-group col-md-12">
      <div class="col-md-10">
            <%= text_field_tag :search, params[:search], 
                                    placeholder: "Recipes", autofocus: true,
                                    class: 'form-control search-box input-lg' %>
      </div>
      <div class="col-md-2">
        <%= button_tag(type: :submit, class: "btn btn-lg btn-success") do %>
           Search Recipe
      <% end %>
    </div>
    <% end %>
  </div>-->

  <%# @recipes.each do |recipe| %>
   <!-- <div><%#= image_tag recipe.image.url(:medium) %></div>
    <div><%#= link_to recipe.name, recipe %></div>
  <%# end %>-->

  <% @recipes.each_slice(3) do |recipes| %>
    <div class="row">
      <% recipes.each do |recipe| %>
        <div class="col-md-4">
          <div>
            <div>
              <%= link_to recipe do %>
                <div class="thumbnail">
                <%= image_tag recipe.image.url(:medium), class: "recipe_image"  %>
                <div class="caption">
                  <h3><%= link_to recipe.name, recipe %></h3>
                  <p>  <%= truncate recipe.description, length: 50 %> </p>
                  <p>      <%= link_to 'read more', recipe %> </p>
                  
                  </p>
                </div>
                </div>
              <% end %>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  <% end %>
</div> <!-- container close -->

app/views/recipes/new.html.erb
<div class="container"> 
	<h1> New Recipe</h1>
		<%= render 'form' %>
	<br>
	<div>
		<%= link_to "Back", root_path, class: "btn btn-default" %>
	</div>
</div>

app/views/recipes/show.html.erb
<div class="container"> 
  <div class="jumbotron">
    <div class="row" id="recipe_top">
      <div class="col-md-4">
        <%= image_tag @recipe.image.url(:medium), class: "recipe_image" %>
      </div>
      <div class="col-md-8">
        <div>
          <h1>
            <%= @recipe.name %>
          </h1>
          <p>
            <%= @recipe.description %>
          </p>
          <p>
            Submitted by
            <%= @recipe.user.email %>
          </p>
          <p>
            <div class="star-rating" data-score= <%= @avg_review %> ></div>
            <em><%= "#{@reviews.length} reviews" %></em>
          </p>
        </div>
      </div>
    </div>
  </div>
  <hr>
  <div>
  <% if @reviews.blank? %>
    <h3>No reviews just yet, would you like to add the first!</h3>
    <%= link_to "Write Review", new_recipe_review_path(@recipe), class: "btn btn-danger" %>
  <% else %>
    <%= link_to "Write Review", new_recipe_review_path(@recipe), class: "btn btn-danger" %>
  <% end %>
  </div>
  <!-- insert here -->
  <div class="row">
    <div class="col-md-8">
      <div>
        <h2>Ingredients</h2>
        <ul>
              <% p=0 %>
              <% c=0 %>
              <% s=0 %>
              <% f=0 %>
              <% @recipe.ingredients.each do |i| %>
                <li><%= i.name %></li>
                <% @search = Openfoodfacts::Product.search(i.name, locale: 'world', page_size: 3) %>
                <% @nutrition = @search.first.fetch %>
                <% @string_to_parse = @nutrition.to_json %>
                <% @hash = JSON.parse(@string_to_parse) %>
                <% protein= (@hash['nutriments']['proteins_100g']).to_f %>
                <% p = protein + p %>
                <% carbohydrates= (@hash['nutriments']['carbohydrates_100g']).to_f %>
                <% c = carbohydrates + c %>
                <% sugars=(@hash['nutriments']['sugars_100g']).to_f %>
                <% s = sugars + s %>
                <% fats=(@hash['nutriments']['fat_100g']).to_f %>
                <% f = fats + f %>
              <% end %>
        </ul>
        <h2> Nutritional Analysis </h2>
              <ul>
                <% no_of_ingredients=@recipe.ingredients.count %>
                <li>Proteins per 100g: <%= p/no_of_ingredients %></li>
                <li>Carbohydrates per 100g: <%= c/no_of_ingredients %></li>
                <li>Sugars per 100g: <%= s/no_of_ingredients %></li>
                <li>Fats per 100g: <%= f/no_of_ingredients %></li>
              </ul>
      </div>
    </div>
  </div> 
  <div class="row">
    <div class="col-md-8">
      <div>
        <h5>Further Details:</h5>
        <table class="table">
          <thead>
            <th>Proteins per 100g</th>
            <th>Carbohydrates per 100g</th>
            <th>Sugars per 100g</th>
            <th>Fats per 100g</th>
          </thead>
          <tbody>
            <tr>
              <% @recipe.ingredients.each do |i| %>
                <td><%= i.name %></td>
                <% @search = Openfoodfacts::Product.search(i.name, locale: 'world', page_size: 3) %>
                <% @nutrition = @search.first.fetch %>
                <% @string_to_parse = @nutrition.to_json %>
                <% @hash = JSON.parse(@string_to_parse) %>
                <td><%= (@hash['nutriments']['proteins_100g']).to_f %></td>
                <td><%= carbohydrates= (@hash['nutriments']['carbohydrates_100g']).to_f %></td>
                <td><%=(@hash['nutriments']['sugars_100g']).to_f %></td>
                <td><%=(@hash['nutriments']['fat_100g']).to_f %></td>
            <tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>



 <!-- insert here -->

  <div class="row">
    <div class="col-md-3">
      <div>
        <h2>Ingredients</h2>
        <ul>
          <% @recipe.ingredients.each do |ingredient| %>
            <li>
              <%= ingredient.name %>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </div> 
  <div class="row">
    <div class="col-md-9">
      <div>
        <h2>Instructions</h2>
        <ul>
          <% @recipe.instructions.each do |instruction, f| %>
            <li>
              <%= instruction.step %>
            </li>
          <% end %>
        </ul>
      </div>
  </div>
  <div class="row">
    <div class="col-md-12">
      <%= link_to "Back", root_path, class: "btn btn-default" %>
      <% if user_signed_in? %>
        <%= link_to "Edit", edit_recipe_path, class: "btn btn-default" %>
        <%= link_to "Delete", recipe_path, method: :delete, data: {confirm: "Are you sure?" }, class: "btn btn-default" %>
      <% end %>
    </div>
  </div>
  <div class="row">
    <div class="col-md-12">
      <h2>Reviews</h2>
      <% @reviews.each do |review| %>
        <div>
          <div class="star-rating" data-score= <%= review.rating %> ></div>
          <p><%= review.comment %></p>
        </div>
        <% end %>
     </div>
  </div>
</div> <!-- close container -->

<script>
    $('.star-rating').raty({
      path: '/assets/',
      readOnly: true,
      score: function() {
            return $(this).attr('data-score');
    }
  });
</script>