config/routes.rb
Rails.application.routes.draw do

  namespace :api, :defaults => {:format => :json} do
    resources :recipes
  end

  devise_for :users, :controllers => { 
    :registrations => "users/registrations",
    :sessions => "sessions"
  }

  as :user do
    post 'sign_in' => 'sessions#create'
    delete 'sign_out' => 'sessions#destroy'
    delete 'logout' => 'sessions#logout'
  end
  
#  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  #root to: "welcome#index"
  resources :recipes do
  	resources :reviews, except: [:show, :index]
  end
#  root "recipes#index"
  root "categories#index"
  get 'search_recipes', to: "recipes#search"
  resources :categories
  resources :ingredients
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord	
	has_many :recipe_ingredients
  has_many :recipes, through: :recipe_ingredients
end

app/controllers/api/ingredients_controller.rb
class Api::IngredientsController < ApplicationController

	def index
		@ingredients = Ingredient.all
		respond_to do |format|
			format.json { render :json => @ingredients }
		end
	end

end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController

	def index
	  @ingredients = Ingredient.all
	end

	def show
	  @ingredient = Ingredient.find(params[:id])
	  @ingredient_recipes = @ingredient.recipes.all
	end

	private
	def ingredient_params
	    params.require(:ingredient).permit(:name)
	end
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/views/ingredients/index.html.erb
<h1>Listing All Ingredients</h1>
  <% @ingredients.each do |i| %>
    <ul>
      <li>
      <%= link_to "#{i.name}", ingredient_path(i) %>
      <li><%= pluralize(i.recipes.count, "recipe") %></li>
      </li>
    </ul>
  <% end %>

  <p><%= link_to 'Back to index', :controller => 'recipes', :action => 'index' %></p>

app/views/ingredients/show.html.erb
<h1><%= "Ingredient: " + @ingredient.name %></h1>

<%= render 'recipes/posting', object: @ingredient_recipes %>