config/routes.rb
Rails.application.routes.draw do

  namespace :api, :defaults => {:format => :json} do
    resources :recipes
  end

  devise_for :users, :controllers => { 
    :registrations => "users/registrations",
    :sessions => "sessions"
  }

  as :user do
    post 'sign_in' => 'sessions#create'
    delete 'sign_out' => 'sessions#destroy'
    delete 'logout' => 'sessions#logout'
  end
  
#  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  #root to: "welcome#index"
  resources :recipes do
  	resources :reviews, except: [:show, :index]
  end
#  root "recipes#index"
  root "categories#index"
  get 'search_recipes', to: "recipes#search"
  resources :categories
  resources :ingredients
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :recipe_categories
  has_many :recipes, through: :recipe_categories

  has_attached_file :image, styles: { :medium => "400x400#" }
	validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

	def index
   @categories = Category.all
  end

  def new
    @category = Category.new
  end
  
  def show
    @category = Category.find(params[:id])
    @category_recipes = @category.recipes.all
  end

def create
    @category = Category.new(category_params)
    if @category.save
      flash[:success] = "Category was created successfully"
      redirect_to categories_path
    else
      render :action => :new
    end
  end
  
  def edit
    @category = Category.find(params[:id])
  end
  
  def update
    @category = Category.find(params[:id])
    if @category.update(category_params)
      flash[:success] = "Category name was successfully updated"
      redirect_to category_path(@category)
    else
      render :action => :edit
    end
  end


  private
  def category_params
    params.require(:category).permit(:name, :image)
  end

end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_category.html.erb
<span><%= link_to category.name, category_path(category) %></span>

app/views/categories/_form.html.erb
<%= form_for(@category) do |f| %>
 <div class="form-group">
    <%= f.file_field :image %>
  </div>
  <%= f.label :name %>
  <%= f.text_field :name, placeholder: "Category name" %>   
  <%= f.submit %>  
<% end %>

<%= link_to "Cancel request", recipes_path %> 

app/views/categories/edit.html.erb
<h1 align="center">Edit Category Name</h1>
<%= render 'form' %>

app/views/categories/index.html.erb
<div class="container"> 
	<h1>Categories</h1>
	<div class="row">
	  <% @categories.each do |category| %>
	  <div class="col-md-4">
	  	<div class="thumbnail">
	    	<%= image_tag category.image.url(:medium), class: "recipe_image"  %>
	     	<div class="caption">
		      <%= link_to "#{category.name}", category_path(category) %>
		      <%#= pluralize(category.recipes.count, "recipe" ) %>
		      <%= (category.recipes.count)   %>
	     	 </div>
	     </div>
	   </div>
	  <% end %>
	</div>

	<p><%#= link_to 'Back to index', :controller => 'recipes', :action => 'index' %></p>
</div>

app/views/categories/new.html.erb
<h1>Create new category</h1>

<%= render 'form' %>

app/views/categories/show.html.erb
<div class="container"> 
	<!--<h1><%#= "Category: " + @category.name %></h1>-->
	<h1><%= @category.name %></h1>
	<%= render 'recipes/post', object: @category_recipes %>
	<%# include admin check to ensure can only edit/create new category %>
	<span><%#= link_to "Edit Category Name", edit_category_path(@category) %></span>
	|
	<span><%#= link_to "Create New Category", new_category_path(@category) %></span>

	 <p><%#= link_to 'Back to index', :controller => 'recipes', :action => 'index' %></p>
</div>