config/routes.rb
Rails.application.routes.draw do

  namespace :api, :defaults => {:format => :json} do
    resources :recipes
  end

  devise_for :users, :controllers => { 
    :registrations => "users/registrations",
    :sessions => "sessions"
  }

  as :user do
    post 'sign_in' => 'sessions#create'
    delete 'sign_out' => 'sessions#destroy'
    delete 'logout' => 'sessions#logout'
  end
  
#  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  #root to: "welcome#index"
  resources :recipes do
  	resources :reviews, except: [:show, :index]
  end
#  root "recipes#index"
  root "categories#index"
  get 'search_recipes', to: "recipes#search"
  resources :categories
  resources :ingredients
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :recipe_categories
  has_many :recipes, through: :recipe_categories

  has_attached_file :image, styles: { :medium => "400x400#" }
	validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord	
	has_many :recipe_ingredients
  has_many :recipes, through: :recipe_ingredients
end

app/models/instruction.rb
class Instruction < ApplicationRecord
  belongs_to :recipe, optional: true
end

app/models/recipe.rb
class Recipe < ApplicationRecord
	belongs_to :user

	has_many :ingredients
	has_many :instructions

	has_many :recipe_categories
  has_many :categories, through: :recipe_categories

  has_many :recipe_ingredients
  has_many :ingredients, through: :recipe_ingredients

  has_many :reviews

	accepts_nested_attributes_for :ingredients,
  								reject_if: proc { |attributes| attributes['name'].blank? },
  								allow_destroy: true
 	accepts_nested_attributes_for :instructions,
  								reject_if: proc { |attributes| attributes['step'].blank? },
  								allow_destroy: true

  validates :name, :description, :image, presence: true

	has_attached_file :image, styles: { :medium => "400x400#" }
	validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/

  def self.search(search)
    where("name LIKE ?", "%#{search}%") 
  end
end

app/models/recipe_category.rb
class RecipeCategory < ApplicationRecord
	belongs_to :recipe
  belongs_to :category
end

app/models/recipe_ingredient.rb
class RecipeIngredient < ActiveRecord::Base
  belongs_to :recipe
  belongs_to :ingredient
end

app/models/review.rb
class Review < ApplicationRecord
	belongs_to :user
	belongs_to :recipe
end

app/models/user.rb
class User < ApplicationRecord
	include UniqueTokenGenerator

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :recipes
	has_many :reviews, dependent: :destroy
  has_attached_file :image, styles: { :medium => "400x400#" }
	validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/

	before_save :ensure_authentication_token

	private

	def ensure_authentication_token
		generate_token_for :authentication_token, token_size: 16
	end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

	def index
   @categories = Category.all
  end

  def new
    @category = Category.new
  end
  
  def show
    @category = Category.find(params[:id])
    @category_recipes = @category.recipes.all
  end

def create
    @category = Category.new(category_params)
    if @category.save
      flash[:success] = "Category was created successfully"
      redirect_to categories_path
    else
      render :action => :new
    end
  end
  
  def edit
    @category = Category.find(params[:id])
  end
  
  def update
    @category = Category.find(params[:id])
    if @category.update(category_params)
      flash[:success] = "Category name was successfully updated"
      redirect_to category_path(@category)
    else
      render :action => :edit
    end
  end


  private
  def category_params
    params.require(:category).permit(:name, :image)
  end

end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
	before_action :find_recipe, only: [:show, :edit, :update, :destroy]
	before_action :authenticate_user!, except: [:index, :show]

	require 'openfoodfacts'
	require 'json'

	def index
		@recipes=Recipe.all
		if params[:search]
			@recipes = Recipe.search(params[:search]).order("created_at DESC")
		else 
			 @recipes = Recipe.all.order('created_at DESC')
		end
	end

	def show
		 @reviews = Review.where(recipe_id: @recipe.id).order("created_at DESC")
		  if @reviews.blank?
      	@avg_review = 0
    	else
      	@avg_review = @reviews.average(:rating).round(2)
    	end
	end

	def new
		@recipe = current_user.recipes.new
		@ingredients = Ingredient.where(hb: true)
	end

	def create
		@recipe = current_user.recipes.new(recipe_params)
		if @recipe.save
			flash[:notice] = "Successfully created a new recipe"
			redirect_to @recipe
		else
			render :action => :new
		end
	end

	def edit
		@ingredients = Ingredient.where(hb: true)
	end

	def update
		if @recipe.update(recipe_params)
			redirect_to @recipe
		else
			render :action => :edit
		end
	end

	def destroy
		@recipe.destroy
		flash[:notice] = "Successfully deleted the recipe"
		redirect_to :action => :index
	end

	private

	def recipe_params
#		params.require(:recipe).permit(:name, :description, :image, :rating, ingredients_attributes: [:id, :name, :_destroy], instructions_attributes: [:id, :step, :_destroy], :ingredient_ids => [], category_ids: [])
		params.require(:recipe).permit(:name, :description, :image, :rating, ingredients_attributes: [:name, :_destroy], instructions_attributes: [:id, :step, :_destroy], :ingredient_ids => [], category_ids: [])
	end

	def find_recipe
		@recipe = Recipe.find(params[:id])
	end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
	before_action :set_review, only: [:show, :edit, :update, :destroy]
  before_action :set_recipe
  before_action :authenticate_user!

  def new
    @review = Review.new
  end

  def edit
  end

  def create
    @review = Review.new(review_params)
    @review.user_id = current_user.id
    @review.recipe_id = @recipe.id

    if @review.save
      redirect_to @recipe
    else
      render :action => :new
    end
  end

  def update
    @review.update(review_params)
  end

  def destroy
    @review.destroy
    redirect_to root_path
  end

  private
    def set_review
      @review = Review.find(params[:id])
    end

    def set_recipe
      @recipe = Recipe.find(params[:recipe_id])
    end

    def review_params
      params.require(:review).permit(:rating, :comment)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < Devise::SessionsController
  include MobileAuthenticationHelper

  skip_before_action :verify_signed_out_user, only: [:destroy]

  def create
    user = warden.authenticate(auth_options)

    if user
      sign_in(:user, user)

      render json: user.as_json(:only => user_render_attrs), status: 200
    else
      render json: {error: 'Incorrect login credentials'} , status: 422
    end
  end

  def destroy
    if is_mobile_app?
      render invalidate_mobile_app_session
      return
    end
    sign_out(:user)
    respond_to_on_destroy
  end

  def logout
    if is_mobile_app?
      render invalidate_mobile_app_session
      return
    end
    sign_out(:user)
    render json: nil
  end

  private
  def user_render_attrs
    attrs = %i(id first_name last_name email address gender)
    attrs << :authentication_token if is_mobile_app?
    attrs
  end

  def invalidate_mobile_app_session
    if current_user
      current_user.update(authentication_token: nil)
      sign_out(:user)
      { status: 204, json: nil }
    else
      { status: 422, json: { error: 'Invalid token.' } }
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
	def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Honestrecipe</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-default">
      <div class="container">
        <div class="navbar-brand">
          <%= link_to image_tag("recibee_logo-02",:size => "100x30",:class => "recibee_img"), root_path %>
          <%#= link_to "Recibee", root_path %>
        </div>
        <%# if user_signed_in? %>
        <% if current_user %>
          <ul class="nav navbar-nav navbar-right">    
              <li>
                <%= form_tag recipes_path, method: :get, class: "navbar-form navbar-right", role: "search" do %>
                  <p>
                    <%= text_field_tag :search, params[:search], class: 'form-control', :cols => 20 %>
                    <%= submit_tag "Search", name: nil, class: "btn btn-default" %>
                  </p>
                <% end %> 
              </li>       
              <li class="nav navbar-text">
                  Welcome <%= current_user.name %>!
              </li>
              <li><%= link_to "New Recipe", new_recipe_path %></li>
              <li><%= link_to "My Profile", edit_registration_path(current_user)  %></li>
              <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Categories <span class="caret"></span></a>
                <ul class="dropdown-menu">
              <li><%= link_to "All Categories", categories_path %></li>
              <% Category.all.each do |category| %>
                <li><%= link_to "#{category.name}", category_path(category) %></li>
              <% end %>
              <li role="separator" class="divider"></li>
              <li><%= link_to "Create New Category", new_category_path %></li>
          </ul>
            </li>
            <li>
              <%= link_to "Sign Out", destroy_user_session_path, method: :delete %>
            </li>
          </ul>
        <% else %>
          <ul class="nav navbar-nav navbar-right">
            <li>
              <%= link_to "Sign Up", new_user_registration_path %>
            </li>
            <li>
              <%= link_to "Sign In", new_user_session_path %>
            </li>
          </ul>
        <% end %>
      </div>
    </nav>
  	<p class="notice"><%= notice %></p>
  	<p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>